train:
  get_spectrogram:
      _target_: torchvision.transforms.v2.Compose
      transforms:
        - _target_: torchaudio.transforms.MelSpectrogram
          sample_rate: 16000
        - _target_: src.transforms.FrequencyMasking
          max_mask_len: 15
          p: 1
        - _target_: src.transforms.TimeMasking
          max_mask_len: 30
          p: 0

  audio:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.Gain
        p: 0
      - _target_: src.transforms.HighPassFilter
        p: 0
        max_cutoff_freq: 900
        min_cutoff_freq: 300
        sample_rate: 16000
      - _target_: src.transforms.LowPassFilter
        p: 0
        max_cutoff_freq: 2100
        min_cutoff_freq: 900
        sample_rate: 16000

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
